[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "EZ EDA"
version = "0.1.0"
authors = [
    { name="Maliek Curtis" }
]
dependencies = [
    "mypy",
    "numpy",
    "pandas",
    "streamlit",
    "pytest"
]

[tool.flake8]
max-line-length = 88
ignore = E203, W503

[tool.black]
max-line-length = 88
